application: pointlesstire
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /.*
  script: main.app


- url: /static
  static_dir: static

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest