application: twcljudge
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:

- url: /static
  static_dir: static
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /screenshot\.png
  static_files: static/screenshot.png
  upload: static/screenshot.png

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
